namespace: "alikins"
name: "collection_inspect"
version: "0.0.17"
license_file: MMMIT.txt
readme: "README.md"
authors:
  - "Adrian Likins <alikins@redhat.com>"
description: "A set of 'collection_inspect' plugins for debugging collection loading"
dependencies:
repository:
documentation:
homepage:
issues:
