namespace: "alikins"
name: "collection_inspect"
version: "0.0.118"
license:
  - MIT
readme: README.md
authors:
  - "Adrian Likins <alikins@redhat.com>"
description: "A set of 'collection_inspect' plugins for debugging collection loading"
dependencies:
repository: https://github.com/alikins/collection_inspect
documentation:
homepage:
issues:
