---
- name: Test alikins.collection_inspect vars plugin
  hosts: localhost
  gather_facts: false
  vars:
    foo: "fooFooFOO"
    # Test having the filter plugin loaded early
    blip: "{{ foo |alikins.collection_inspect.collection_inspect }}"
  tasks:
    - name: "Test collection_inspect module and module_utils loaded from alikins.collection_inspect collection"
      alikins.collection_inspect.collection_inspect:
        args:
      register: module_result

    - name: Show collection_inspect module results
      debug:
        var: module_result

    # TODO: not sure if vars plugins are expected to work yet
    - name: show vars plugins for collection_inspect
      debug:
        msg: "{{ vars|to_nice_json }}"
